### ISSUE TITLE
About deploying polkaj_ The method of schnorkel native JNI

### ISSUE THREAD

**Issue by LmingXie** [emeraldpay/polkaj#17]
```
Library /native/windows/polkaj_schnorrkel.dll is not found in the classpath
Failed to load native library. Polkaj Schnorrkel methods are unavailable. Error: no polkaj_schnorrkel in java.library.path....
Exception in thread "main" java.lang.UnsatisfiedLinkError: common.utils.Schnorrkel.keypairFromSeed([B)[B
```
Hello!
  When I run and call 'generatekeypair()', there is a lack of schnorkel JNI library. Can you provide me with the deployment method of schnorkel JNI? Thank you very much.

**Comment by splix** [comment]
It's not published anywhere yet, and is still in development. To use it in your code you have to make a local build of the library. To do so you need to install Rust and Cargo (https://rustup.rs/), then run `gradle install` which would make the build and install it into the local repo. 

Please note though, that the jar will be built for the local OS, and cannot be used on a machine with different OS after compilation. I'm working on providing a build including libs for major OSes

**Comment by LmingXie** [comment]
Thank you for your reply. I've built it.Through ```cargo build``` to build JNI and modify the ```System.loadLibrary (libname)``` path.

**Comment by splix** [comment]
It shouldn't be necessary to make build with `cargo` manually, because there is a Gradle task which should run Cargo and pack the native lib into the jar (so you wouldn't need to modify library paths). 

The Gradle task (`compileRust`) runs automatically each time you recompile the sources, and when you do local `gradle install`. If it didn't work for you, please let me know. I'm still working on Schnorrkel module, so may be there are some issues.
