### ISSUE TITLE
rewrite polkaj to java10,  it appears some warnings in SchnorrkelNative

### ISSUE THREAD

**Issue by BomaxChen** [emeraldpay/polkaj#28]
Hi, 
Cause my environment is java10, so I try to rewrite your polkaj to jdk10.0.2
But I don't change anything at SchnorrkelNative,  I use these libraries in my maven project,  then it pops out warning below:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access using Lookup on io.emeraldpay.polkaj.schnorrkel.SchnorrkelNative (file:/Users/bomaxchen/.m2/repository/io/emeraldpay/polkaj/polkaj-schnorrkel/0.5.1/polkaj-schnorrkel-0.5.1.jar) to class java.lang.ClassLoader
WARNING: Please consider reporting this to the maintainers of io.emeraldpay.polkaj.schnorrkel.SchnorrkelNative
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

======

althought it doesn't happen error and it can run transfer using http-api , but i'm curious how to solve it.   Thank you !

**Comment by splix** [comment]
I'm not sure at this moment, but I think I have it too even on Java 11. I'm using some _hacks_ with reflection to setup Schnorrkel, so it probably gives such warning. It works though, so I didn't pay much attention because other ways would be even more ugly.

Btw, why Java 10? I target 11 as current LTS, but I'm open to discuss possible release compatible with earlier JVMs, if it makes sense for many.

**Comment by BomaxChen** [comment]
i try many times using java10 version polkaj,  it doesn't appear problems, maybe i'll keep monitoring this java10 library.

And because our project use java10, I've try compile polkaj with java11 and use it in java10 project, but it can't run cause version issue.

Thank you !
