### ISSUE TITLE
Can't run examples

### ISSUE THREAD

**Issue by nschwermann** [emeraldpay/polkaj#46]
In order to run examples I had to edit gradle wrapper from version 6.1 to 6.3 and I also had to update polkaJ version from 0.4.0-snapshot to 0.3.0 because the snapshot is not being hosted in bintray.

**Comment by splix** [comment]
If you have a different version of the Gradle just use it as is. I.e. just `gradle <command>`. 
Bundled `./gradlew` wrapper script is useful, in my opinion, only when you don't have any Gradle installed so it installs it on the first run. Otherwise just use any version you already have.

You can run `gradle install` in root directory of the project to build and install _snapshot_ locally, and 0.4.0-SNAPSHOT would work after that.

**Comment by nschwermann** [comment]
Thanks okay yes running gradle install now I can run examples with snapshot.  Running my installed gradle does work, but I do believe the wrapper files need to be updated to version 6.3 to work. At least for my configuration they do. I have java 15.0.1 on Big Sur and gradle 6.8

**Comment by nschwermann** [comment]
@splix any idea on the error for balance I posted?

**Comment by nschwermann** [comment]
Have resolved examples not running will be included in next pr

**Comment by paulvi** [comment]
I ran into the same 

This `examples\common.gradle` is misleading:

If we use SNAPSHOT versions, that requires running `gradle install`,  
then repository entry is not needed.

```gradle
//
// Common config for Polkaj Examples
//
ext {
   polkajVersion = "0.4.0-SNAPSHOT"
}

repositories {
   // polkaj public repo
   maven { url  "https://dl.bintray.com/emerald/polkaj" }
}
```
